### ISSUE TITLE
Brenda 2012 REACTION entry

### ISSUE THREAD

**Issue by ivan-krukov** [Midnighter/BRENDA-Parser#1]
In the latest BRENDA version (downloaded 17-07-2012), line 3049469 throws the following exception:

<pre><code>
    Traceback (most recent call last):
    File "<stdin>", line 2, in <module>
    File "brenda_parser.py", line 289, in parse self._parse_information_field(line)
    File "brenda_parser.py", line 302, in _parse_information_field self._line_number)
    brenda_parser.ArgumentError: unrecognised entry: '  (#2,4# cyclization reaction <7>)' @ #3049469
</code></pre>

The region in the file looks like so:

<pre><code>
REACTION
RE  (2E,6E)-farnesyl diphosphate = (+)-delta-cadinene + diphosphate

    (#2,4# cyclization reaction <7>)

REACTION_TYPE
RT  cyclization (#2# elimination of diphosphate <12>)
RT  elimination of diphosphate
</code></pre>

Should there be a clause for this?
Would removing the empty line fix this?

**Comment by ivan-krukov** [comment]
Removing the block (empty line and (#2,4#...)) allows the file to be parsed completely.
Removing only the empty line results in hanging of the program. While in the "hung" state, the memory consumption is high (up to 1GB).
So this appears to be a single occurrence of this empty line problem.
Should this just be reported to the BRENDA curators?

**Comment by Midnighter** [comment]
I removed the complete line and it worked just fine. Maybe in removing the line you also removed the white space at the beginning of the next line? That would cause an error.

Thank you for noting the issue here, I will put it in the readme.

If you were to mention the problem to the curators that might help future releases of the text version.

**Comment by ivan-krukov** [comment]
Thank you very much.
I found your parser really useful.
Sincerely,
Ivan K
On Jul 17, 2012 7:15 PM, "Moritz Emanuel Beber" <
reply@reply.github.com>
wrote:
