### ISSUE TITLE
Argument Error

### ISSUE THREAD

**Issue by daMogli** [Midnighter/BRENDA-Parser#2]
When I delete the line before the error i get this error:

brenda_parser.ArgumentError: unrecognised entry: '
' @ #8

**Comment by Midnighter** [comment]
Can you supply a little more information please? What BRENDA file version are you parsing? When you say that you "delete the line before the error", what error are you referring to?

**Comment by daMogli** [comment]
brenda_parser.ArgumentError: unrecognised entry: '  (#2,4# cyclization reaction <7>)' @ #3049469
is the orignal error. so like the other thread says I delete the blank line before.
I am parsing the current BRENDA file version.

**Comment by Midnighter** [comment]
OK, so why do you now get an error with line 8? Did you change anything else in the file? When deleting the empty line, did you make sure to preserve the tab before "(#2,4# cyclization reaction )"?

**Comment by daMogli** [comment]
I did not change anything else and the tab is still there

**Comment by Midnighter** [comment]
So I re-downloaded the latest version of BRENDA, deleted the empty line, and parsing was successful. Is this still an issue for you?

**Comment by Midnighter** [comment]
With the latest update you should see no more errors due to file formatting. Feedback would be appreciated.
