### ISSUE TITLE
parsing errors

### ISSUE THREAD

**Issue by leihuang** [Midnighter/BRENDA-Parser#3]
For the Brenda text data file downloaded on May-10-2013, the parser has problems handling lines ending with any of the following strings:

"{?", "{" "{r", "{ir", "{i", "{ie". 

In all cases the line has the right curly bracket "}" immediately following it. 

Removing the line break string "\n" so that the right curly bracket matches the left one on the same line resolves the problem. 

P.S., thank you for the parser Midnighter.

**Comment by Midnighter** [comment]
Hi, I changed the parser. Now it ends and entry/section only when coming across a new entry/section or the enzyme entry ends. This makes the parser robust against format errors. Please let me know about any other bugs you may discover.
